# Generated by Django 3.1.8 on 2021-07-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetupapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
