# Generated by Django 3.1.8 on 2021-07-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetupapp', '0003_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
