# Generated by Django 3.1.8 on 2021-07-28 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetupapp', '0005_job_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='creator',
            field=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='event_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetup',
            name='followers',
            field=models.ManyToManyField(related_name='meetuppost', to=settings.AUTH_USER_MODEL),
        ),
    ]
