# Generated by Django 3.1.8 on 2021-07-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetupapp', '0011_auto_20210729_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='end_date',
            field=models.TimeField(),
        ),
    ]
